<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.zhangheng.record</groupId>
    <artifactId>LiveMonitoringRecording</artifactId>
    <version>3.6</version>
    <packaging>pom</packaging>
    <description>【星曦向荣】直播录屏工具</description>
    <modules>
        <module>douyin-start</module>
        <module>bilibili-start</module>
        <module>live-common</module>
        <module>live-monitor-record</module>
        <module>kuaishou-start</module>
        <!--该模块为可选，可直接注释掉-->
        <!--<module>activation-tool</module>-->
        <module>browser-utils</module>
        <module>douyin-fetcher</module>
        <module>cpolar-tool</module>
    </modules>

    <properties>
        <xxxr.version>3.6</xxxr.version>
        <project.encoding>UTF-8</project.encoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>${project.encoding}</project.build.sourceEncoding>
        <project.reporting.outputEncoding>${project.encoding}</project.reporting.outputEncoding>
        <maven.compiler.encoding>${project.encoding}</maven.compiler.encoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
    </properties>

    <developers>
        <developer>
            <name>星曦向荣</name>
            <email>zhangheng_0805@163.com</email>
            <url>https://github.com/ZhangHeng0805</url>
        </developer>
    </developers>

    <dependencies>
        <!-- mvn install:install-file -Dfile=libs/ZH_Utils.jar -DgroupId=com.zhangheng -DartifactId=ZH_Utils -Dversion=26.06.07 -Dpackaging=jar -->
        <dependency>
            <groupId>com.zhangheng</groupId>
            <artifactId>ZH_Utils</artifactId>
            <version>26.06.07</version>
        </dependency>

        <!-- Logback 作为 SLF4J 的实现 -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>

        <!-- Lombok 依赖 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.36</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <!-- 指定JDK编译版本 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <encoding>${project.encoding}</encoding>
                    </configuration>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>
</project>